language: node_js
node_js: node
services:
- mongodb
deploy:
  api_key:
    secure: Rhw//i3VLuLcqVIjPk8y7mefLOaEnIDdtfai3Xtb+Jr+vmyf8oGc9N+cXZJZ8TT7wMxS+6WXk448P2CP4sTv/Ni3ssfMUCXyuTLNWGvHr0OaJAvzBkY9A685gaewgm4Jfoo6eroeSBzz/U8dluFrAVJVZXRmX0SdqjzdiyMTvTD7pWdSr83G1FX1gEMWWWiUpnsFZvAltSD+/rpGupntAd2XVKiw+nj4emu7ZYrGY5pFAZA7sYyYJI+Sgwr5zIIVcgSib2lLnAlHnxofXEAKnQT2agHbzqxo0B9OolgN7Wq7m71vT4kKNVm4BNWlfUrpF9VR4p6UIAKOy1UA9vHeY7QedPihFvROVxBm+Sv3Y3c6qWFgKXOTVwnJrD4RAJzXnZS2bt+lFtUy5kU5K/63kaZynv2ZvWJYRa1ihRb7OZEZkCYyHJ9g7wlHfyrNrm24OQOASOmJYMtRf34zsDmr6z5/w5TwdLqCsJzSgnc1S4j8qJOn9SWhto59U3MaXl9RJB1+wqgWoTDzo8yYY+1XcrnLre9oynEtoQ8wOIuD9ieV3H2gNTI0PhK0G+1aVeR5u4FtcaSa3Z2yu1UJ3Wm0b7S6N31hGaKN+rHXw9GtXmtMk2Eo7qDvUEIPHsCCG8fHl9FamW6ajFH6Wh/gSvZbX95gxMlnYr0mXbkaQlMzPAY=
